### ISSUE TITLE
All form fields show up but you can't enter text

### ISSUE THREAD

**Issue by geoffreystevens** [MastodonC/kixi.hecuba#573]
Im still having trouble creating properties. I have got as far as the form but im locked out of editing any of the fields:

http://www.getembed.com/app#511d6530-f227-4279-be56-93e95283e41a,158dc07f-6450-4615-ab41-233b92225eeb

**Comment by geoffreystevens** [comment]
i seemed to be blocked out of editing all forms - including editing profile infromation

**Comment by otfrom** [comment]
lein was out of date on the servers and causing lein clean to fail. I've updated lein, but the problem isn't completely solved.

Now you can edit things in text areas, but text fields don't show what is typed into them. However, when you hit save, your edits are actually saved to the server and show up on refresh.
